### ISSUE TITLE
feature request: more output on startup

### ISSUE THREAD

**Issue by rdp** [mynyml/watchr#8]
Currently (maybe because I'm on windows so anticipate anything ruby having a startup pause time), with watchr, when I start it on a script I am left wondering "has it started yet?"

E:\installs\ruby191p376\lib\ruby\gems\1.9.1\gems\redcar-0.3.2dev>watchr -d go.watchr
 # unsure that it is done loading or not.

suggestion:
add a message by default, like
E:\installs\ruby191p376\lib\ruby\gems\1.9.1\gems\redcar-0.3.2dev>watchr -d go.watchr
Started watching x files.

Or add one in debug, like

E:\installs\ruby191p376\lib\ruby\gems\1.9.1\gems\redcar-0.3.2dev>watchr -d go.watchr
[watchr debug] using Watchr::EventHandler::Portable handler
[watchr debug] loaded script file "E:/installs/ruby191p376/lib/ruby/gems/1.9.1/gems/redcar-0.3.2dev/go.watchr"
[watchr debug] watching 60 files

or what not.
That would be awesome.
Thanks!
-r

**Comment by mynyml** [comment]
I'd rather keep the output clean of noise so that everything it controlled by the user. If you need the feedback, you could add a `puts "loaded"` statement at the bottom of your .watchr file.

As for the debug mode output, the "loaded script file" statement is printed at the end of the loading cycle (right before entering the listening loop) so it already serves the purpose of letting you know you're ready to go.
